### ISSUE TITLE
"Invalid regular expression" when quote character is a backslash 

### ISSUE THREAD

**Issue by jobe451** [adaltas/node-csv-stringify#107]
I have to produce a CSV, where the quote character is a backslash (\\). I can define quite a wide range of quotation charcters, however when defining a backspace, things fail:

Stringifier config:
```JSON
{
    "delimiter": "|",
    "header": true,
    "quoted": true,
    "quote": "\\"
}
```
Error:

```
uncaughtException SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at Stringifier.stringify (C:\xyz\node_modules\csv-stringify\lib\index.js:358:20)
    at Stringifier.write (C:\xyz\node_modules\csv-stringify\lib\index.js:264:20)
    at CsvStringifier._write (C:\xyz\src\stringifiers\CsvStringifier.js:31:25)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    ...
```

**Comment by wdavidw** [comment]
Could you please provide a mininam sample reproducing your issue. Thank you.

**Comment by wdavidw** [comment]
Lack of activity, closing. Feel free to re-open with a sample.
