### ISSUE TITLE
Support for Node 10.4+ BigInt

### ISSUE THREAD

**Issue by colinfindlay-nz** [adaltas/node-csv-stringify#110]
**Describe the bug**

Serializing data on Node 12 with any BigInt datatypes produces

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Stringifier.stringify (/var/task/node_modules/csv-stringify/lib/index.js:335:136)
    at Stringifier._transform (/var/task/node_modules/csv-stringify/lib/index.js:230:20)
    at Stringifier.Transform._read (_stream_transform.js:191:10)
    at Stringifier.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Stringifier.Writable.write (_stream_writable.js:316:11)
    at module.exports (/var/task/node_modules/csv-stringify/lib/sync.js:18:17)

**To Reproduce**

Something like:
`csvstringify([{"myBigNumber": new BigInt(123)}]);`

**Comment by wdavidw** [comment]
Not sure there is something I can do about.

**Comment by wdavidw** [comment]
Thank you for reporting this issue. I just realized that BigInt was not a build-in JS object but a type. It makes complete sense to support it and there is not incompatibility with how with deal with objects. Release 5.5.0 is out with BigInt support.

**Comment by colinfindlay-nz** [comment]
Thank you so much! You're awesome!
