### ISSUE TITLE
Error ERR_STREAM_WRITE_AFTER_END on second run 

### ISSUE THREAD

**Issue by gitowiec** [adaltas/node-csv-stringify#119]
I have this code:
```typescript

  async run(unsortedCsvFilesList: string[]): Promise<string> {
    const csvFilesList = unsortedCsvFilesList.sort(naturalCompare);
    const jobId = getReqId();
    const jobUnzipTargetFilePath = `${this.defaultTransformerSourceFilePath}/${jobId}`;

    const Multistream = require('multistream');
    const fullFileNamePathsToStream = (filenamePaths: string[]) => {
      return new Multistream(filenamePaths.map(path => fs.createReadStream(path)));
    };

    const filesStream = fullFileNamePathsToStream(csvFilesList.map(fileName => `${jobUnzipTargetFilePath}/${fileName}`));

    await mkdirPromised(`${this.defaultTransformerDestinationFilePath}/${jobId}`, { recursive: true });

    const { getSchemaTransformer, stringifier } = require('transformers/src');

    try {

      getSchemaTransformer('mBiznesExCsv')
        .reduce((acc, transformer) => acc.pipe(transformer), filesStream)
        .pipe(stringifier)
        .pipe(
          fs.createWriteStream(`${this.defaultTransformerDestinationFilePath}/${jobId}/download.csv`)
        );
    } catch (error) {
      this.logger.error(error,'oh crap');
    }

    return jobId;
  }

```
It is the method stored in use case class inside tsoa NodeJS application with InversifyJS.
`getSchemaTransformer` returns transformer made with mississippi module. `stringifier` is `csv-stringify` module.

`stringifier` is:
```
const stringify = require('csv-stringify');
export const stringifier = stringify({
  header: false,
  delimiter: ',',
  quoted_string: true,
  quoted_empty: true,
});
```

It works ok for the first time.

But every second run it crashes with
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Stringifier.Writable.write (_stream_writable.js:296:5)
    at DestroyableTransform.ondata (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at addChunk (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at DestroyableTransform._transform (/home/user/workspace/bank-statement-csv-processor/node_modules/transformers/src/mapResultsRowToRow.ts:20:3)
    at DestroyableTransform.Transform._read (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/home/user/workspace/bank-statement-csv-processor/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Transformer.ondata (_stream_readable.js:709:20)
    at Transformer.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Transformer.Readable.push (_stream_readable.js:224:10)
    at Transformer.Transform.push (_stream_transform.js:151:32)
    at Transformer.__done (/home/user/workspace/bank-statement-csv-processor/node_modules/stream-transform/lib/index.js:181:12)
19:10:57.136Z  INFO bank-statement-csv-processor-server: got closed (serviceIdentifier=FileUploadUseCase, appEnv=local, reqId=91972b00-1f9a-11eb-9f0a-adaa2d9db9a9)
 
``` 

I managed to "repair" this error by instantiating `stringifier` once every call to `run` method by wrapping its code with arrow function like this

`stringifier` is:
```
const stringify = require('csv-stringify');
export const stringifier = ()=> stringify({
  header: false,
  delimiter: ',',
  quoted_string: true,
  quoted_empty: true,
});
```

**Comment by wdavidw** [comment]
This package implements the stream.Transform native Node.js API. It is been so for the last 6 or 8 years and no bug like above have been reported. With the little of information provided above, I will consider the problem is coming from the outside such as the stream writing to the stringifier.
