### ISSUE TITLE
csv-stringify Node JS Sample programs not running 

### ISSUE THREAD

**Issue by mohitgoyal007** [adaltas/node-csv-stringify#55]
Hi,

I have downloaded the latest  ["csv-stringify": "^2.0.0"] node libraries and while running the samples I am getting below issues:

/home/ec2-user/tpco.it.rclog/node_modules/csv-stringify/lib/index.js:86
Stringifier = function(opts = {}) {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ec2-user/tpco.it.rclog/node_modules/csv-stringify/samples/api.stream.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

It looks like the library has some issue

Please help in resolving the same

**Comment by wdavidw** [comment]
Closing, sorry that I forgot to get back to you. You were using an old version of Node.js.
